version: "3.7"

services:
  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgres://postgres:CcACCbbCD442114dbC1eGfc2C653gcc1@switchback.proxy.rlwy.net:19354/railway"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000