version: "3.7"

services:
  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      SECRET_KEY: "${SECRET_KEY}"
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000
