version: "3.7"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
